runtime: nodejs12 # or another supported version

instance_class: F1

handlers:
- url: /static
  static_dir: build/static

- url: /favicon.gif
  static_files: build/favicon.gif
  upload: build/favicon.gif

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  redirect_http_response_code: 301
  secure: always