steps:
- name: node:$_NODE_VERSION
  entrypoint: yarn
  args: ['install']

- name: node:$_NODE_VERSION
  entrypoint: yarn
  args: ['webpack', '--mode=$_MODE']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
timeout: '1600s'

