name: Cypress Tests

on: 
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npx webpack serve --mode=development